name: Continuous Integration & Delivery

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install firebase tools
        run: npm install -g firebase-tools

      - name: install dependencies
        run: npm install

      - name: rebuild
        run: npm rebuild

      - name: list variables
        run: env

      - name: run tests with firebase emulator
        run: firebase emulators:exec 'npm run test' --token ${{ secrets.FIREBASE_TOKEN }}

#      - name: start firebase emulators with test script
#        uses: w9jds/firebase-action@master
#        with:
#          args: emulators:exec 'npm run test'
#        env:
#          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  build:
    needs: test
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      - name: build project
        run: npm run build

      - name: archive artifact
        uses: actions/upload-artifact@master
        with:
          name: www
          path: www

  deploy_preview:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: download artifact
        uses: actions/download-artifact@master
        with:
          name: www
          path: www

      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy ${{ github.event.number }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: download artifact
        uses: actions/download-artifact@master
        with:
          name: www
          path: www

      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
